/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityScopedUserProfile {
  'name' : string,
  'activities' : Array<string>,
  'socialNetworkLinks' : Array<string>,
  'services' : Array<string>,
}
export interface PersistentEventView {
  'id' : string,
  'startTime' : bigint,
  'endTime' : bigint,
  'name' : string,
  'community' : string,
  'committee' : Array<Principal>,
  'isActive' : boolean,
}
export interface Position { 'x' : number, 'y' : number }
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'links' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'contributeToConstruction' : ActorMethod<[string, Position], undefined>,
  'createCommunity' : ActorMethod<[string, [] | [string]], string>,
  'createEvent' : ActorMethod<
    [string, string, Array<Principal>, bigint, bigint, boolean, string],
    undefined
  >,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'getActiveConstruction' : ActorMethod<[string], [] | [Array<Position>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityMap' : ActorMethod<[string], Array<[Principal, Position]>>,
  'getCommunityScopedUserProfile' : ActorMethod<
    [string, Principal],
    [] | [CommunityScopedUserProfile]
  >,
  'getCompletedConstructions' : ActorMethod<[string], Array<Position>>,
  'getPersistentActiveEvent' : ActorMethod<
    [string],
    [] | [PersistentEventView]
  >,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserEligibleForEvent' : ActorMethod<[string, Principal], boolean>,
  'joinCommunity' : ActorMethod<[string], undefined>,
  'listCommunities' : ActorMethod<[], Array<[string, [] | [string]]>>,
  'listCommunityMembers' : ActorMethod<[string], Array<Principal>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCommunityScopedUserProfile' : ActorMethod<
    [string, CommunityScopedUserProfile],
    undefined
  >,
  'setBuildEligibility' : ActorMethod<[string, Principal, boolean], undefined>,
  'updateEventStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];