/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Position = IDL.Record({ 'x' : IDL.Nat32, 'y' : IDL.Nat32 });
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'links' : IDL.Vec(IDL.Text),
});
export const CommunityScopedUserProfile = IDL.Record({
  'name' : IDL.Text,
  'activities' : IDL.Vec(IDL.Text),
  'socialNetworkLinks' : IDL.Vec(IDL.Text),
  'services' : IDL.Vec(IDL.Text),
});
export const PersistentEventView = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Nat64,
  'endTime' : IDL.Nat64,
  'name' : IDL.Text,
  'community' : IDL.Text,
  'committee' : IDL.Vec(IDL.Principal),
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'contributeToConstruction' : IDL.Func([IDL.Text, Position], [], []),
  'createCommunity' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Principal),
        IDL.Nat64,
        IDL.Nat64,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getActiveConstruction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Position))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityMap' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Position))],
      ['query'],
    ),
  'getCommunityScopedUserProfile' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Opt(CommunityScopedUserProfile)],
      ['query'],
    ),
  'getCompletedConstructions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Position)],
      ['query'],
    ),
  'getPersistentActiveEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PersistentEventView)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserEligibleForEvent' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'joinCommunity' : IDL.Func([IDL.Text], [], []),
  'listCommunities' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(IDL.Text)))],
      ['query'],
    ),
  'listCommunityMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCommunityScopedUserProfile' : IDL.Func(
      [IDL.Text, CommunityScopedUserProfile],
      [],
      [],
    ),
  'setBuildEligibility' : IDL.Func([IDL.Text, IDL.Principal, IDL.Bool], [], []),
  'updateEventStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Position = IDL.Record({ 'x' : IDL.Nat32, 'y' : IDL.Nat32 });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'links' : IDL.Vec(IDL.Text),
  });
  const CommunityScopedUserProfile = IDL.Record({
    'name' : IDL.Text,
    'activities' : IDL.Vec(IDL.Text),
    'socialNetworkLinks' : IDL.Vec(IDL.Text),
    'services' : IDL.Vec(IDL.Text),
  });
  const PersistentEventView = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Nat64,
    'endTime' : IDL.Nat64,
    'name' : IDL.Text,
    'community' : IDL.Text,
    'committee' : IDL.Vec(IDL.Principal),
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'contributeToConstruction' : IDL.Func([IDL.Text, Position], [], []),
    'createCommunity' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Principal),
          IDL.Nat64,
          IDL.Nat64,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getActiveConstruction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Position))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityMap' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Position))],
        ['query'],
      ),
    'getCommunityScopedUserProfile' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Opt(CommunityScopedUserProfile)],
        ['query'],
      ),
    'getCompletedConstructions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Position)],
        ['query'],
      ),
    'getPersistentActiveEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersistentEventView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserEligibleForEvent' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'joinCommunity' : IDL.Func([IDL.Text], [], []),
    'listCommunities' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(IDL.Text)))],
        ['query'],
      ),
    'listCommunityMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCommunityScopedUserProfile' : IDL.Func(
        [IDL.Text, CommunityScopedUserProfile],
        [],
        [],
      ),
    'setBuildEligibility' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
    'updateEventStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };