/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Position {
    x: number;
    y: number;
}
export interface PersistentEventView {
    id: string;
    startTime: bigint;
    endTime: bigint;
    name: string;
    community: string;
    committee: Array<Principal>;
    isActive: boolean;
}
export interface UserProfile {
    bio: string;
    displayName: string;
    links: Array<string>;
}
export interface CommunityScopedUserProfile {
    name: string;
    activities: Array<string>;
    socialNetworkLinks: Array<string>;
    services: Array<string>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    contributeToConstruction(eventId: string, part: Position): Promise<void>;
    createCommunity(name: string, description: string | null): Promise<string>;
    createEvent(id: string, name: string, committee: Array<Principal>, startTime: bigint, endTime: bigint, isActive: boolean, community: string): Promise<void>;
    createOrUpdateProfile(displayName: string, bio: string, links: Array<string>): Promise<void>;
    getActiveConstruction(communityName: string): Promise<Array<Position> | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityMap(communityName: string): Promise<Array<[Principal, Position]>>;
    getCommunityScopedUserProfile(communityName: string, user: Principal): Promise<CommunityScopedUserProfile | null>;
    getCompletedConstructions(communityName: string): Promise<Array<Position>>;
    getPersistentActiveEvent(communityName: string): Promise<PersistentEventView | null>;
    getProfile(user: Principal): Promise<UserProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isUserEligibleForEvent(eventId: string, user: Principal): Promise<boolean>;
    joinCommunity(communityName: string): Promise<void>;
    listCommunities(): Promise<Array<[string, string | null]>>;
    listCommunityMembers(communityName: string): Promise<Array<Principal>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCommunityScopedUserProfile(communityName: string, profile: CommunityScopedUserProfile): Promise<void>;
    setBuildEligibility(eventId: string, user: Principal, wantsToBuild: boolean): Promise<void>;
    updateEventStatus(eventId: string, isActive: boolean): Promise<void>;
}
import type { CommunityScopedUserProfile as _CommunityScopedUserProfile, PersistentEventView as _PersistentEventView, Position as _Position, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async contributeToConstruction(arg0: string, arg1: Position): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.contributeToConstruction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.contributeToConstruction(arg0, arg1);
            return result;
        }
    }
    async createCommunity(arg0: string, arg1: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunity(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunity(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: Array<Principal>, arg3: bigint, arg4: bigint, arg5: boolean, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async getActiveConstruction(arg0: string): Promise<Array<Position> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveConstruction(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveConstruction(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityMap(arg0: string): Promise<Array<[Principal, Position]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityMap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityMap(arg0);
            return result;
        }
    }
    async getCommunityScopedUserProfile(arg0: string, arg1: Principal): Promise<CommunityScopedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityScopedUserProfile(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityScopedUserProfile(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedConstructions(arg0: string): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedConstructions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedConstructions(arg0);
            return result;
        }
    }
    async getPersistentActiveEvent(arg0: string): Promise<PersistentEventView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersistentActiveEvent(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersistentActiveEvent(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserEligibleForEvent(arg0: string, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserEligibleForEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserEligibleForEvent(arg0, arg1);
            return result;
        }
    }
    async joinCommunity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinCommunity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinCommunity(arg0);
            return result;
        }
    }
    async listCommunities(): Promise<Array<[string, string | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommunities();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommunities();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCommunityMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommunityMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommunityMembers(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCommunityScopedUserProfile(arg0: string, arg1: CommunityScopedUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCommunityScopedUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCommunityScopedUserProfile(arg0, arg1);
            return result;
        }
    }
    async setBuildEligibility(arg0: string, arg1: Principal, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBuildEligibility(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBuildEligibility(arg0, arg1, arg2);
            return result;
        }
    }
    async updateEventStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEventStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEventStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Position>]): Array<Position> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommunityScopedUserProfile]): CommunityScopedUserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersistentEventView]): PersistentEventView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_tuple_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, [] | [string]]): [string, string | null] {
    return [
        value[0],
        from_candid_opt_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, [] | [string]]>): Array<[string, string | null]> {
    return value.map((x)=>from_candid_tuple_n11(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
